// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: serviceB.proto

/*
Package serviceA is a generated protocol buffer package.

It is generated from these files:
	serviceB.proto

It has these top-level messages:
	AddToQueueRequest
	AddToQueueResponse
	AckMessageRequest
	AckMessageResponse
	RabbitMQRequest
	RabbitMQResponse
*/
package serviceA

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ServiceB service

type ServiceBService interface {
	AddToQueue(ctx context.Context, in *AddToQueueRequest, opts ...client.CallOption) (*AddToQueueResponse, error)
	AckMessage(ctx context.Context, in *AckMessageRequest, opts ...client.CallOption) (*AckMessageResponse, error)
}

type serviceBService struct {
	c    client.Client
	name string
}

func NewServiceBService(name string, c client.Client) ServiceBService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "serviceA"
	}
	return &serviceBService{
		c:    c,
		name: name,
	}
}

func (c *serviceBService) AddToQueue(ctx context.Context, in *AddToQueueRequest, opts ...client.CallOption) (*AddToQueueResponse, error) {
	req := c.c.NewRequest(c.name, "ServiceB.AddToQueue", in)
	out := new(AddToQueueResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceBService) AckMessage(ctx context.Context, in *AckMessageRequest, opts ...client.CallOption) (*AckMessageResponse, error) {
	req := c.c.NewRequest(c.name, "ServiceB.AckMessage", in)
	out := new(AckMessageResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ServiceB service

type ServiceBHandler interface {
	AddToQueue(context.Context, *AddToQueueRequest, *AddToQueueResponse) error
	AckMessage(context.Context, *AckMessageRequest, *AckMessageResponse) error
}

func RegisterServiceBHandler(s server.Server, hdlr ServiceBHandler, opts ...server.HandlerOption) error {
	type serviceB interface {
		AddToQueue(ctx context.Context, in *AddToQueueRequest, out *AddToQueueResponse) error
		AckMessage(ctx context.Context, in *AckMessageRequest, out *AckMessageResponse) error
	}
	type ServiceB struct {
		serviceB
	}
	h := &serviceBHandler{hdlr}
	return s.Handle(s.NewHandler(&ServiceB{h}, opts...))
}

type serviceBHandler struct {
	ServiceBHandler
}

func (h *serviceBHandler) AddToQueue(ctx context.Context, in *AddToQueueRequest, out *AddToQueueResponse) error {
	return h.ServiceBHandler.AddToQueue(ctx, in, out)
}

func (h *serviceBHandler) AckMessage(ctx context.Context, in *AckMessageRequest, out *AckMessageResponse) error {
	return h.ServiceBHandler.AckMessage(ctx, in, out)
}
