// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serviceB.proto

package serviceA

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AckMessageRequest struct {
	MessageId            string   `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckMessageRequest) Reset()         { *m = AckMessageRequest{} }
func (m *AckMessageRequest) String() string { return proto.CompactTextString(m) }
func (*AckMessageRequest) ProtoMessage()    {}
func (*AckMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_serviceB_518cdcd575eb92ff, []int{0}
}
func (m *AckMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckMessageRequest.Unmarshal(m, b)
}
func (m *AckMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckMessageRequest.Marshal(b, m, deterministic)
}
func (dst *AckMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckMessageRequest.Merge(dst, src)
}
func (m *AckMessageRequest) XXX_Size() int {
	return xxx_messageInfo_AckMessageRequest.Size(m)
}
func (m *AckMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AckMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AckMessageRequest proto.InternalMessageInfo

func (m *AckMessageRequest) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

type AckMessageResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckMessageResponse) Reset()         { *m = AckMessageResponse{} }
func (m *AckMessageResponse) String() string { return proto.CompactTextString(m) }
func (*AckMessageResponse) ProtoMessage()    {}
func (*AckMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_serviceB_518cdcd575eb92ff, []int{1}
}
func (m *AckMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckMessageResponse.Unmarshal(m, b)
}
func (m *AckMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckMessageResponse.Marshal(b, m, deterministic)
}
func (dst *AckMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckMessageResponse.Merge(dst, src)
}
func (m *AckMessageResponse) XXX_Size() int {
	return xxx_messageInfo_AckMessageResponse.Size(m)
}
func (m *AckMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckMessageResponse proto.InternalMessageInfo

func (m *AckMessageResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type RabbitMQRequest struct {
	MessageId            string   `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RabbitMQRequest) Reset()         { *m = RabbitMQRequest{} }
func (m *RabbitMQRequest) String() string { return proto.CompactTextString(m) }
func (*RabbitMQRequest) ProtoMessage()    {}
func (*RabbitMQRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_serviceB_518cdcd575eb92ff, []int{2}
}
func (m *RabbitMQRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RabbitMQRequest.Unmarshal(m, b)
}
func (m *RabbitMQRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RabbitMQRequest.Marshal(b, m, deterministic)
}
func (dst *RabbitMQRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RabbitMQRequest.Merge(dst, src)
}
func (m *RabbitMQRequest) XXX_Size() int {
	return xxx_messageInfo_RabbitMQRequest.Size(m)
}
func (m *RabbitMQRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RabbitMQRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RabbitMQRequest proto.InternalMessageInfo

func (m *RabbitMQRequest) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *RabbitMQRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RabbitMQResponse struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RabbitMQResponse) Reset()         { *m = RabbitMQResponse{} }
func (m *RabbitMQResponse) String() string { return proto.CompactTextString(m) }
func (*RabbitMQResponse) ProtoMessage()    {}
func (*RabbitMQResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_serviceB_518cdcd575eb92ff, []int{3}
}
func (m *RabbitMQResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RabbitMQResponse.Unmarshal(m, b)
}
func (m *RabbitMQResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RabbitMQResponse.Marshal(b, m, deterministic)
}
func (dst *RabbitMQResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RabbitMQResponse.Merge(dst, src)
}
func (m *RabbitMQResponse) XXX_Size() int {
	return xxx_messageInfo_RabbitMQResponse.Size(m)
}
func (m *RabbitMQResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RabbitMQResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RabbitMQResponse proto.InternalMessageInfo

func (m *RabbitMQResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func init() {
	proto.RegisterType((*AckMessageRequest)(nil), "serviceA.AckMessageRequest")
	proto.RegisterType((*AckMessageResponse)(nil), "serviceA.AckMessageResponse")
	proto.RegisterType((*RabbitMQRequest)(nil), "serviceA.RabbitMQRequest")
	proto.RegisterType((*RabbitMQResponse)(nil), "serviceA.RabbitMQResponse")
}

func init() { proto.RegisterFile("serviceB.proto", fileDescriptor_serviceB_518cdcd575eb92ff) }

var fileDescriptor_serviceB_518cdcd575eb92ff = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x75, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf2, 0x1d, 0x95,
	0x0c, 0xb9, 0x04, 0x1d, 0x93, 0xb3, 0x7d, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x83, 0x52, 0x0b,
	0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x64, 0xb8, 0x38, 0x73, 0x21, 0x22, 0x9e, 0x29, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x08, 0x01, 0x25, 0x1d, 0x2e, 0x21, 0x64, 0x2d, 0xc5, 0x05, 0xf9, 0x79,
	0xc5, 0xa9, 0x42, 0x62, 0x5c, 0x6c, 0xc5, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x50, 0x0d, 0x50, 0x9e,
	0x92, 0x33, 0x17, 0x7f, 0x50, 0x62, 0x52, 0x52, 0x66, 0x89, 0x6f, 0x20, 0x51, 0xc6, 0x0b, 0x09,
	0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x81, 0x25, 0xc0, 0x6c, 0x25, 0x3d, 0x2e, 0x01,
	0x84, 0x21, 0x50, 0x0b, 0xa5, 0xb8, 0x38, 0xd2, 0x8b, 0x52, 0x53, 0x4b, 0x32, 0xf3, 0xd2, 0xa1,
	0x86, 0xc0, 0xf9, 0x46, 0xa1, 0x5c, 0x30, 0x1f, 0x3a, 0x09, 0x79, 0x72, 0x71, 0x21, 0x9c, 0x2b,
	0x24, 0xad, 0x07, 0xf3, 0xba, 0x1e, 0x86, 0xbf, 0xa5, 0x64, 0xb0, 0x4b, 0x42, 0x2c, 0x54, 0x62,
	0x48, 0x62, 0x03, 0x87, 0x9e, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xaa, 0x32, 0x53, 0x4f,
	0x01, 0x00, 0x00,
}
